version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_CONNECTION=mysql
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "3000:4000"
    volumes:
      - .:app/
      - app/node_modules
    depends_on:
      - mongo
      - mysql

  mysql:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/data/mysql-db
    networks:
      - private

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - private

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - private
      
networks: -private
volumes:
  mongo-data:
  mysql-data:
